server:
  port: 8090

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/technologies_microservice
    username: rootaa
    password: Alvaro15
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update