server:
  port: 8090

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bootcamp2024
    username: ${username}
    password: ${password}
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update